databases:
  - name: sarfees-db
    plan: free
    databaseName: sarfees_db
    user: sarfees_user

services:
  - type: web
    name: sarfees-api
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: sarfees-db
          property: dpg-d7dckqf7f7vs73errg0g-a
      - key: DB_PORT
        fromDatabase:
          name: sarfees-db
          property: 5432
      - key: DB_USERNAME
        fromDatabase:
          name: sarfees-db
          property: sarfees_db_user
      - key: DB_PASSWORD
        fromDatabase:
          name: sarfees-db
          property: OdY46ROXxdqOTKGHyOiQclVL69cmzcrl
      - key: DB_NAME
        fromDatabase:
          name: sarfees-db
          property: sarfees_db
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
