export enum TripStatus {
  PENDING = 'PENDING',
  MATCHED = 'MATCHED',
  DRIVER_EN_ROUTE = 'DRIVER_EN_ROUTE',
  ARRIVED_AT_PICKUP = 'ARRIVED_AT_PICKUP',
  TRIP_IN_PROGRESS = 'TRIP_IN_PROGRESS',
  ARRIVING_AT_DROPOFF = 'ARRIVING_AT_DROPOFF',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
